In [6]:
import numpy as np

In [7]:
import pandas as pd

In [8]:
movies = pd.read_csv('../data/tmdb_5000_movies.csv')
credits= pd.read_csv('../data/tmdb_5000_credits.csv')

In [9]:
movies.sample(3)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
3300,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,220488,"[{""id"": 12354, ""name"": ""hong kong""}, {""id"": 18...",zh,非常幸运,My Lucky Star is a 2013 Chinese romance film d...,1.864530,"[{""name"": ""Bona International Film Group"", ""id...","[{""iso_3166_1"": ""CN"", ""name"": ""China""}]",2013-09-17,0,114.0,"[{""iso_639_1"": ""zh"", ""name"": ""\u666e\u901a\u8b...",Released,NaN,My Lucky Star,4.3,8
2665,14200000,"[{""id"": 18, ""name"": ""Drama""}]",NaN,1951,"[{""id"": 531, ""name"": ""southern usa""}, {""id"": 2...",da,Manderlay,"In 1933, after leaving Dogville, Grace Margare...",7.051450,"[{""name"": ""Zentropa Entertainments"", ""id"": 76}...","[{""iso_3166_1"": ""DK"", ""name"": ""Denmark""}, {""is...",2005-05-16,674918,139.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Liberation. Whether They Want It Or Not.,Manderlay,6.9,78
3324,7500000,"[{""id"": 35, ""name"": ""Comedy""}]",NaN,103903,"[{""id"": 3525, ""name"": ""racehorse""}]",en,Outside Bet,A group of print workers in 1980s London club ...,0.086731,[],"[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""}]",2012-04-27,0,101.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,Outside Bet,5.8,2

In [10]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [11]:
## merging the two datasets
movies.shape

(4803, 20)

In [12]:
credits.shape

(4803, 4)

In [13]:
movies = movies.merge(credits,on='title')

In [14]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [15]:


# we dont need all of the columns
# genres
# id
# keywords
# title
# overview
# cast
# crew

movies = movies[['genres','id','keywords','title','overview','cast','crew']]

In [16]:
movies.head()

,genres,id,keywords,title,overview,cast,crew
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",Spectre,A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",John Carter,"John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [17]:
movies.isna().sum()

genres      0
id          0
keywords    0
title       0
overview    3
cast        0
crew        0
dtype: int64

In [18]:
movies.dropna(inplace=True)

In [19]:
movies.isna().sum()

genres      0
id          0
keywords    0
title       0
overview    0
cast        0
crew        0
dtype: int64

In [20]:
movies.duplicated().sum()

np.int64(0)

In [21]:
movies['genres'][0]
# note that the list is in the form of a string

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [22]:
# so, we have to convert the string into list first, then extract the genres as intended
import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [23]:
def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [24]:
movies['genres'] = movies['genres'].apply(convert)

In [25]:
movies.head()

,genres,id,keywords,title,overview,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[Adventure, Fantasy, Action]",285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[Action, Adventure, Crime]",206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",Spectre,A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[Action, Crime, Drama, Thriller]",49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[Action, Adventure, Science Fiction]",49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",John Carter,"John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [26]:
movies['keywords']

0       [{"id": 1463, "name": "culture clash"}, {"id":...
1       [{"id": 270, "name": "ocean"}, {"id": 726, "na...
2       [{"id": 470, "name": "spy"}, {"id": 818, "name...
3       [{"id": 849, "name": "dc comics"}, {"id": 853,...
4       [{"id": 818, "name": "based on novel"}, {"id":...
                              ...
4804    [{"id": 5616, "name": "united states\u2013mexi...
4805                                                   []
4806    [{"id": 248, "name": "date"}, {"id": 699, "nam...
4807                                                   []
4808    [{"id": 1523, "name": "obsession"}, {"id": 224...
Name: keywords, Length: 4806, dtype: object

In [27]:
movies['keywords'] = movies['keywords'].apply(convert)

In [28]:
movies.head()

,genres,id,keywords,title,overview,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...",Spectre,A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[Action, Crime, Drama, Thriller]",49026,"[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[Action, Adventure, Science Fiction]",49529,"[based on novel, mars, medallion, space travel...",John Carter,"John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [29]:
# we only need top 3 actors and the name of the director
movies['cast'][0]
def convertcast(obj):
    L = []
    obj = ast.literal_eval(obj)
    counter = 0
    for i in obj:
        if counter==3: break
        L.append(i['name'])
        counter+=1
    return L

In [30]:
movies['cast'] = movies['cast'].apply(convertcast)

In [31]:
movies.head()

,genres,id,keywords,title,overview,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...",Spectre,A cryptic message from Bond’s past sends him o...,"[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[Action, Crime, Drama, Thriller]",49026,"[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[Action, Adventure, Science Fiction]",49529,"[based on novel, mars, medallion, space travel...",John Carter,"John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [32]:
movies['crew'][0]
def convertCrew(obj):
    L = []
    for i in ast.literal_eval(obj):
        if(i['job']=='Director'):
            L.append(i['name'])
            return L

In [33]:
movies['crew'] = movies['crew'].apply(convertCrew)

In [34]:
movies.head()

,genres,id,keywords,title,overview,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...",Spectre,A cryptic message from Bond’s past sends him o...,"[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,"[Action, Crime, Drama, Thriller]",49026,"[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,"[Action, Adventure, Science Fiction]",49529,"[based on novel, mars, medallion, space travel...",John Carter,"John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [35]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [36]:
movies.head()

,genres,id,keywords,title,overview,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...",Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,"[Action, Crime, Drama, Thriller]",49026,"[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,"[Action, Adventure, Science Fiction]",49529,"[based on novel, mars, medallion, space travel...",John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [37]:
# now, we have to remove the spcae between cast's first and last name
# as if didnt do that, for eg. in the models, two tags will be created for 'Chris Hemsworth'-->'Chris','Hemsworth'
# so now, if any person likes the movies of CH, the movies of 'Chris Evans' will also get recommended, as both have the 'Chris' tag in them
# WE DON'T want this, so we make separate tags as--> 'ChrisHemsworth', 'ChrisEvans' to avoid the mixup

movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])

In [38]:
movies.head()

,genres,id,keywords,title,overview,cast,crew
0,"[Action, Adventure, Fantasy, ScienceFiction]",19995,"[cultureclash, future, spacewar, spacecolony, ...",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[James Cameron]
1,"[Adventure, Fantasy, Action]",285,"[ocean, drugabuse, exoticisland, eastindiatrad...",Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[Gore Verbinski]
2,"[Action, Adventure, Crime]",206647,"[spy, basedonnovel, secretagent, sequel, mi6, ...",Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[Sam Mendes]
3,"[Action, Crime, Drama, Thriller]",49026,"[dccomics, crimefighter, terrorist, secretiden...",The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[ChristianBale, MichaelCaine, GaryOldman]",[Christopher Nolan]
4,"[Action, Adventure, ScienceFiction]",49529,"[basedonnovel, mars, medallion, spacetravel, p...",John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[Andrew Stanton]

In [39]:
movies[movies.isna().any(axis=1)]

,genres,id,keywords,title,overview,cast,crew
3665,[Drama],19615,[],Flying By,"[A, real, estate, developer, goes, to, his, 25...","[BillyRayCyrus, HeatherLocklear, AhnaiseChrist...",None
3674,[Family],447027,[],Running Forever,"[After, being, estranged, since, her, mother's...",[],None
3734,"[Drama, Family, Foreign]",26379,[],Paa,"[He, suffers, from, a, progeria, like, syndrom...","[AmitabhBachchan, AbhishekBachchan, VidyaBalan]",None
3982,"[Comedy, Drama, Romance]",55831,[independentfilm],Boynton Beach Club,"[A, handful, of, men, and, women, of, a, certa...","[BrendaVaccaro, DyanCannon, JosephBologna]",None
4073,[],371085,[],Sharkskin,"[The, Post, War, II, story, of, Manhattan, bor...",[],None
4110,[],48382,[],"The Book of Mormon Movie, Volume 1: The Journey","[The, story, of, Lehi, and, his, wife, Sariah,...","[KirbyHeyborne, MichaelFlynn]",None
4123,[],325140,[],Hum To Mohabbat Karega,"[Raju,, a, waiter,, is, in, love, with, the, f...",[],None
4128,"[Animation, Family, Foreign]",20653,[],Roadside Romeo,"[This, is, the, story, of, Romeo., A, dude, wh...","[SaifAliKhan, KareenaKapoor, JavedJaffrey]",None
4252,"[Romance, Comedy, Drama]",361505,[],Me You and Five Bucks,"[A, womanizing, yet, lovable, loser,, Charlie,...",[],None
4311,"[Comedy, Music]",114065,[],Down & Out With The Dolls,"[The, raunchy,, spunky, tale, of, the, rise, a...",[],None
4320,[],137955,[],Crowsnest,"[In, late, summer, of, 2011,, five, young, fri...",[],None
4328,[Documentary],102840,[],Sex With Strangers,"[For, some, married, couples,, sex, is, an, ob...",[],None
4380,[Comedy],47686,[independentfilm],Dream with the Fishes,"[Terry, is, a, suicidal, voyeur, who, treats, ...","[DavidArquette, BradHunt, KathrynErbe]",None
4407,"[Action, Comedy, ScienceFiction]",43630,[],The Helix... Loaded,[],[],None
4411,"[Family, Comedy]",357441,[],Karachi se Lahore,"[A, road, trip, from, Karachi, to, Lahore, whe...","[ShehzadSheikh, AyeshaOmar, YasirHussain]",None
4464,[],279759,[],Harrison Montgomery,"[Film, from, Daniel, Davila]",[],None
4510,[],331493,[],Light from the Darkroom,"[Light, in, the, Darkroom, is, the, story, of,...",[],None
4559,[],380097,[],America Is Still the Place,"[1971, post, civil, rights, San, Francisco, se...",[],None
4568,[],297100,[],The Little Ponderosa Zoo,"[The, Little, Ponderosa, Zoo, is, preparing, f...",[],None
4572,[],325579,[],Diamond Ruff,"[Action, -, Orphan,, con, artist,, crime, boss...",[],None
4577,[],328307,[],Rise of the Entrepreneur: The Search for a Bet...,"[The, world, is, changing, faster, than, ever....",[],None
4589,[Documentary],47546,[],I Want Your Money,"[Two, versions, of, the, American, dream, now,...",[],None
4595,"[Drama, Mystery, Thriller]",43743,[independentfilm],Fabled,"[Joseph, just, broke, up, with, his, girlfrien...",[],None
4639,[],300327,[],Death Calls,"[An, action-packed, love, story, on, the, Mexi...",[],None
4644,"[Drama, Action, Crime]",378237,[],Amidst the Devil's Wings,"[Prequel, to, ""5th, of, a, Degree.""]",[],None
4650,[Horror],325123,[],Teeth and Blood,"[A, beautiful, diva, is, murdered, on, the, se...","[GlennPlummer, MichelleVanDerWater, DanielleVega]",None
4663,[],320435,[],UnDivided,"[UnDivided, documents, the, true, story, of, h...",[],None
4668,[Comedy],40963,[independentfilm],Little Big Top,"[An, aging, out, of, work, clown, returns, to,...","[SidHaig, RichardRiehle, MelEngland]",None
4680,[],194588,[],Short Cut to Nirvana: Kumbh Mela,"[Every, 12, years, over, 70, million, pilgrims...",[],None
4722,[],38786,[],The Blood of My Brother: A Story of Death in Iraq,"[THE, BLOOD, OF, MY, BROTHER, goes, behind, th...",[],None

In [40]:
movies.isna().sum() # this is only those with NaN value, empty lists are not shown here

genres       0
id           0
keywords     0
title        0
overview     0
cast         0
crew        30
dtype: int64

In [41]:
movies = movies.dropna()

In [42]:
movies.isna().sum()

genres      0
id          0
keywords    0
title       0
overview    0
cast        0
crew        0
dtype: int64

In [43]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [44]:
movies.head()

,genres,id,keywords,title,overview,cast,crew,tags
0,"[Action, Adventure, Fantasy, ScienceFiction]",19995,"[cultureclash, future, spacewar, spacecolony, ...",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[James Cameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,"[Adventure, Fantasy, Action]",285,"[ocean, drugabuse, exoticisland, eastindiatrad...",Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[Gore Verbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,"[Action, Adventure, Crime]",206647,"[spy, basedonnovel, secretagent, sequel, mi6, ...",Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[Sam Mendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,"[Action, Crime, Drama, Thriller]",49026,"[dccomics, crimefighter, terrorist, secretiden...",The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[ChristianBale, MichaelCaine, GaryOldman]",[Christopher Nolan],"[Following, the, death, of, District, Attorney..."
4,"[Action, Adventure, ScienceFiction]",49529,"[basedonnovel, mars, medallion, spacetravel, p...",John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[Andrew Stanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [45]:
new_df = movies[['id','title','tags']]

In [46]:
new_df.head()

,id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [47]:
# convert tags into string
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

/tmp/ipykernel_808/3919116817.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

In [48]:
new_df.head()

,id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [49]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver James Cameron'

In [50]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

/tmp/ipykernel_808/3214958533.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [51]:
new_df.head()

,id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

## Now we have to do the VECTORIZATION of tags

so basically, we have to convert text(tags) to vectors
this is called text-vectorization
Every movie will have its own corresponding vector,and we'll recommend the movies which have vectors nearby
the movie user watched

https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html

In [52]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=5000,stop_words='english')# stop_words attribute will remove the words of english language(like as, in, the, a etc.)

note that, here the max_features=5000 means that we have chosen top 5000 words from the dataset for the vectorization of movies(excluding english words)

In [53]:
vectors = cv.fit_transform(new_df['tags']).toarray()## by default, it is a sparse matx., we explictly convert it to numpy array

In [54]:
print(vectors)
print(vectors.shape)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(4776, 5000)

In [55]:
pd.DataFrame(cv.get_feature_names_out().tolist()).head(50)

                 0
0              000
1              007
2               10
3              100
4               11
5               12
6               13
7               14
8               15
9               16
10              17
11            17th
12              18
13            18th
14     18thcentury
15              19
16           1930s
17           1940s
18           1950s
19           1960s
20           1970s
21            1980
22           1980s
23            1985
24           1990s
25            19th
26     19thcentury
27              20
28             200
29            2009
30            20th
31              24
32              25
33              30
34             300
35              3d
36              40
37              50
38             500
39              60
40             60s
41           aaron
42    aaroneckhart
43       abandoned
44        abducted
45  abigailbreslin
46       abilities
47         ability
48            able
49          aboard

we can notice a problem here, both words ability and abilities, actor and actors,etc. as both means the same but are listed differently..

In [56]:
# ['loving','love','loved'] --> ['love','love','love']
import nltk # natural processing lib.
# basically it will convert the word into its ROOT-word

In [57]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [58]:
def stem(text):
    y = []

    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [59]:
ps.stem('loving')

'love'

In [60]:
ps.stem('loved')

'love'

In [61]:
ps.stem('actors')

'actor'

In [62]:
new_df['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver james cameron'

In [63]:
stem('in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver james cameron')

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jame cameron'

In [64]:
new_df['tags'] = new_df['tags'].apply(stem)

/tmp/ipykernel_808/3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [65]:
new_df['tags'][5]

"the seemingli invinc spider-man goe up against an all-new crop of villain – includ the shape-shift sandman. while spider-man’ superpow are alter by an alien organism, hi alter ego, peter parker, deal with nemesi eddi brock and also get caught up in a love triangle. fantasi action adventur dualident amnesia sandstorm loveofone'slif forgiv spider wretch deathofafriend egomania sand narcism hostil marvelcom sequel superhero reveng tobeymaguir kirstendunst jamesfranco sam raimi"

In [66]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [67]:
vectors.shape

(4776, 5000)

In [68]:
pd.DataFrame(cv.get_feature_names_out().tolist()).head(60)

                 0
0              000
1              007
2               10
3              100
4               11
5               12
6               13
7               14
8               15
9               16
10              17
11              18
12            18th
13     18thcenturi
14              19
15            1910
16            1920
17            1930
18            1940
19            1944
20            1950
21           1950s
22            1960
23           1960s
24            1970
25           1970s
26            1974
27            1976
28            1980
29            1985
30            1990
31            1999
32            19th
33     19thcenturi
34              20
35             200
36            2003
37            2009
38            20th
39            21st
40              23
41              24
42              25
43              30
44             300
45              3d
46              40
47              50
48             500
49              60
50              70
51           aaron
52    aaroneckhart
53         abandon
54          abduct
55  abigailbreslin
56            abil
57             abl
58          aboard
59            abov

in higher dimensions , euclidean distance fails
so instead, we use cosine distance b/w movie vectors as a form of comparision

In [69]:
from sklearn.metrics.pairwise import cosine_similarity

In [70]:
similarity = cosine_similarity(vectors)

In [71]:
similarity[0]

array([1.        , 0.08119979, 0.0836242 , ..., 0.04399059, 0.        ,
       0.        ])

In [72]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(2405, np.float64(0.28644594961577313)),
 (1214, np.float64(0.2811237422961876)),
 (3726, np.float64(0.25715142542972574)),
 (507, np.float64(0.25016291953504993)),
 (1202, np.float64(0.24419314525275215))]

In [73]:
def recommend(movie):
    movie_index = new_df[new_df['title']==movie].index[0]
    distances = similarity[movie_index]
    # note that by sorting distances, we will lose the index position of the movies in the similarity matx,
    # thats why we will use enumerate function to store the index values
    movie_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]

    for i in movie_list:
        print(new_df.iloc[i[0]].title)

In [74]:
recommend('Avatar')

Aliens
Aliens vs Predator: Requiem
Falcon Rising
Independence Day
Predators

In [75]:
recommend('The Avengers')

Avengers: Age of Ultron
Iron Man 3
Captain America: Civil War
Captain America: The First Avenger
Iron Man

In [76]:
recommend('Just Married')

Tom Jones
Silent House
Must Love Dogs
Sarah's Key
Heartbeeps

In [77]:
recommend('Batman Begins')

The Dark Knight
Batman
The Dark Knight Rises
Batman
10th & Wolf

In [78]:
import pickle

In [79]:
pickle.dump(new_df.to_dict(), open('../models/movie_dict.pkl', 'wb'))

In [80]:
pickle.dump(similarity, open('../models/similarity.pkl', 'wb'))